version: '3.9'
services:
    postgres:
        container_name: postgres
        image: postgres:14-alpine
        volumes:
            - db-data:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - '9090:5432'

volumes:
    db-data:
        driver: local
