### REGISTER ADMIN
POST http://localhost:8080/api/v1/users/admin/register
Accept: application/json
Content-Type: application/json

{
  "shop_name": "vandesar",
  "email": "vandesar123@gmail.com",
  "password": "vandesarASDA123@213"
}

### LOGIN admin
POST http://localhost:8080/api/v1/users/admin/login
Accept: application/json
Content-Type: application/json

{
  "email": "vandesar123@gmail.com",
  "password": "vandesarASDA123@213"
}

### REGISTER CASHIER
POST http://localhost:8080/api/v1/users/cashier/register
Accept: application/json
Content-Type: application/json

{
  "username": "sam",
  "password": "vandesarASDA123@213"
}

### LOGIN CASHIER
POST http://localhost:8080/api/v1/users/cashier/login
Accept: application/json
Content-Type: application/json

{
  "username": "sam",
  "password": "vandesarASDA123@213"
}